# Machine executor, set the machine key to true in .circleci/config.yml:
version: 2.1
orbs:
  secrethub: secrethub/cli@1.0.0
jobs:
  build_and_publish:
    docker:
      - image: 'node:14.15.0-stretch'
    # environment:
      # EXAMPLE_ENV_VAR: 5.27.1
    steps:
      - checkout
      - secrethub/install
      - run:
          name: "Checking git cloned files"
          command: |
                    git status
                    ls -allh .
      - run: # print the name of the branch we're on
          name: "What branch am I on ?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "Run Tests"
          command: |
                    npm i
                    npm run test
      - run: # print the name of the branch we're on
          name: "Build package"
          command: |
                    npm run build
      - run: # print the name of the branch we're on
          name: "Publish to NPM Registry"
          command: |
                    npm run build
                    export LOCAL_SECRET_FILE=${HOME}/.npmrc
                    secrethub read --out-file "${LOCAL_SECRET_FILE}" "${SECRETHUB_ORG}/${SECRETHUB_REPO}/meta/gclio/npm-registries/npmjs.org/npmrc"
                    npm publish

workflows:
  version: 2.1
  build_and_publish:
    jobs:
      - build_and_publish:
          context: cicd-gclio
          filters:
            branches:
              ignore:
                - master
                - develop
                - /^feature\/*/
                - /^support\/*/
                - /^bugfix\/*/
                - /^hotfix\/*/
                - /^release\/*/
            tags:
              # only: /^v.*/
              only:
                - /^[0-999].[0-999].[0-999]/
                - /^[0-999].[0-999].[0-999]-alpha/
                - /^[0-999].[0-999].[0-999]-beta/
